# Commands
BOT_COMMANDS = [
    ("start", "Check bot status"),
    ("aidetect", "Detect AI-generated image"),
    ("aitext", "Detect AI-generated text"),
    ("donate", "Support bot"),
    ("help", "Show help menu"),
    ("settings", "User settings"),
    ("nobg", "Remove background"),
    ("upscale", "Upscale image"),
    ("quiz", "Random quiz"),
    ("ping", "Check latency"),
    ("kang", "Add sticker to pack"),
    ("ship", "Choose couple"),
    ("quoteanime", "Random anime quote"),
    ("susunkata", "Play word arrangement game"),
    ("stats", "System statistics"),
    ("dl", "Download video"),
    ("manga", "Read manga"),
    ("ask", "Ask Gemini AI"),
    ("music", "Search music"),
    ("caca", "Chat with Caca"),
    ("groq", "Ask Groq AI"),
    ("gsearch", "Google search"),
    ("asupan", "Random asupan"),
    ("tr", "Translate text"),
]
