import logging

log = logging.getLogger(__name__)

ASUPAN_DB_PATH = "data/asupan.sqlite3"

ASUPAN_PREFETCH_SIZE = 7
ASUPAN_AUTO_DELETE_SEC = 1800
ASUPAN_COOLDOWN_SEC = 5

DEFAULT_ASUPAN_KEYWORDS = [
    "acaawra0",
    "ayaa_1a6",
    "vlencyah_",
    "estehmanisanget071",
    "78user550",
    "kindiii1_",
    "shel_ytta",
    "kailaa.nii",
    "tasyaa_191",
    "ceacantik3",
    "samanthaawaa",
    "_micinn__",
    "memeycantik022",
    "putihabuabuah",
    "clrviia",
    "ellmaviraw",
    "zarraa3742",
    "user112055011",
    "4vign",
    "nanaaheni_",
    "mesiemess",
    "jejeyyyyy46",
    "paninaa_13",
    "dwycantikadewi",
    "nadineabgail",
    "arakedua__",
    "cebelassimutt",
    "dee308550",
    "kecoa.imuttt",
    "notmeyy._",
    "ssnappy1",
    "vbynad_ia",
    "anglcin",
    "jeeyaniwhs",
    "nazilaa0_",
    "princessvionaa",
    "annaatsyaca_",
    "user150612018306",
    "cutedouyin01",
    "notriissaaa",
    "capybarinnn",
    "noncakeith",
    "zayaofficial2",
    "fluffyaa_",
    "nylasetilia",
    "nikenandalusia",
    "tarankaaa",
    "gebirieru",
    "duhsirachel",
    "dearizkyer",
    "verllyaling_",
    "saylviee",
    "aurynlrz",
    "thatsenjaaaa",
    "thatsenjaaaa",
    "bhn.ctr",
    "userrimutt_1708",
    "ulannny",
    "pnanngrnii_",
    "meyturuu_",
    "pptri726",
    "ayu69842",
    "cantikacacaaa",
    "itatay0ow_",
    "shrk_dar",
    "mieaiyamsatu",
    "usrnme2009",
    "z4h_ra06",
    "iyaininovajuga",
    "titikcrewett",
    "njelll0ii",
    "olinnn230",
    "inimarheta",
    "ameliaputri402",
    "pikaaw.ns",
    "grilssfaa",
    "rynsawaw",
    "_venzo21",
    "ntsa.bn",
    "cacaaaja39",
    "bancolmu0",
    "teerzas",
    "danisaanr",
    "mellyn022",
    "ecceuuu",
    "callistaaraww",
    "auliaaizumiii_",
    "inipavanaml24",
    "tante holic",
    "alaa.sabillaa",
    "meyturuu_",
    "urvelsyn",
    "user94772038",
    "araasshr",
    "sweetykidiepy_",
    "keiz1a",
    "tataaasiuu20",
    "nasluvt",
    "dimpledtataww",
    "lvme4awaa",
    "liveid63",
    "cewe cantik",
    "cewe sma",
    "rerereyaaa",
    "cewe smp",
    "cewe tanktop",
    "#tanteholic",
    "shsshlla",
    "Seeazeee",
    "iniitataajugaa_",
    "billaazz",
    "innova.kasih.4",
    "tobrut",
    "tanktopstyle",
    "tanktop",
    "zaraxhel",
    "verllyyaling",
    "eunicetjoaa",
]